print ("Hello world")
print ("Hello Again")
print ("I like typing this.")
print ("This is fun.")
print ("Yay! Printing.")
print ('Yay! Printing.')
print ("I'd much rather you 'not'.")
print ("I \"said\" don't touch this.")
print ('''Tshis is a paragraph and it starts with three single quotes and end with three single quotes''')
print ("I don't know 'Heineken'.")